// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr712EsqMCGt50VB7ePKY0lowrSV04Mro',
    appId: '1:478209484436:web:0fc8cf3fed5678c7aa7681',
    messagingSenderId: '478209484436',
    projectId: 'bloc-ecommerce-app-bf3ca',
    authDomain: 'bloc-ecommerce-app-bf3ca.firebaseapp.com',
    storageBucket: 'bloc-ecommerce-app-bf3ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9TP2P0KxPEJ-WLPdR0SCfKxl98vEPeDE',
    appId: '1:478209484436:android:058372386205e5f8aa7681',
    messagingSenderId: '478209484436',
    projectId: 'bloc-ecommerce-app-bf3ca',
    storageBucket: 'bloc-ecommerce-app-bf3ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANg5T4yLCV_7HCo52mL97ktM1S_1mXMKM',
    appId: '1:478209484436:ios:fad1a4da67f6f03daa7681',
    messagingSenderId: '478209484436',
    projectId: 'bloc-ecommerce-app-bf3ca',
    storageBucket: 'bloc-ecommerce-app-bf3ca.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
